apiVersion: v1
kind: PersistentVolume
metadata:
 name: fast-nfs-pv-sql0
 labels:
   type: nfs-model-storage
spec:
 capacity:
   storage: 1Ti
 accessModes:
   - ReadWriteOnce
 persistentVolumeReclaimPolicy: Retain
 mountOptions:
   - nconnect=8
   - nfsvers=3
 nfs:
   server: "192.168.20.13"
   path: "/mnt/fast/mysql/data0"
