apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: fast-nfs-pvc
 namespace: default
spec:
 storageClassName: ""
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 1Ti
 selector:
   matchLabels:
     type: nfs-model-storage
