apiVersion: v1
kind: PersistentVolume
metadata:
 name: infra-nfs-pv-sql1
 labels:
   type: nfs-model-storage
spec:
 storageClassName: ""
 capacity:
   storage: 1Ti
 accessModes:
   - ReadWriteOnce
 persistentVolumeReclaimPolicy: Retain
 mountOptions:
   - nconnect=8
   - nfsvers=3
 nfs:
   server: "192.168.20.13"
   path: "/mnt/infra/mysql/data1"
