apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
  namespace: minio
  labels:
    app.kubernetes.io/instance: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  volumeMode: Filesystem
