apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  labels:
    app.kubernetes.io/instance: minio
spec:
  claimRef:
    name: minio
    namespace: minio
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "192.168.20.13"
    path: "/mnt/fast/workspaces/minio"
