apiVersion: v1
kind: PersistentVolume
metadata:
  name: polaris-postgres-pv
  labels:
    app.kubernetes.io/instance: polaris
spec:
  claimRef:
    name: data-polaris-postgres-postgresql-0
    namespace: polaris
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "192.168.20.13"
    path: "/mnt/fast/workspaces/polaris/postgresql"
