
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockalgop
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: stockalgo
  template:
    metadata:
      labels: 
        app: stockalgo
    spec:
      volumes:
        - name: fastdata
          persistentVolumeClaim:
            claimName: fast-nfs-pvc
      containers:
        - name: stockalgop
          image: marcpaulthecoder/stockalgo
          command: ["sleep", "infinity"]
          volumeMounts:
            - name: fastdata
              mountPath: /srv/nas/fast
